name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0.1.0
        with:
          trust-check: false

      - name: Check Linting
        run: selene .

  format:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Aftman
        uses: ok-nick/setup-aftman@v0.1.0
        with:
          trust-check: false

      - name: Check Formatting
        run: stylua --check .
